# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

## Will Build/Test if no tag
## Will Build/Release if tagged

name: Build/Test or Build/Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
          matrix:
            openrefine_version: ["3.7.2", "3.8.1"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dopenrefine.version=${{ matrix.openrefine_version }}
    
    - name: Set version string output variable
      id: version_string_variable
      run: echo "output_value=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./packaging/target/refine-groovy-${{ steps.version_string_variable.outputs.output_value }}.zip
        release_name: ${{ github.ref }}
        body: ${{ github.event.release.body }}
        draft: false
        prerelease: false